name = "kura"
badges = ["github-actions/test.yml", "coveralls", "metacpan"]
authority = "cpan:KFLY"
module_maker="ModuleBuildTiny"
static_install = "auto"

markdown_maker = "Pod::Markdown::Github"

[release]
branch = "main"
