name: test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl:
          [
            "5.40",
            "5.38",
            "5.36",
            "5.34",
            "5.32",
            "5.30",
            "5.28",
            "5.26",
            "5.24",
            "5.22",
            "5.20",
            "5.18",
            "5.16",
          ]
        include:
          - perl: 5.40
            coverage: true
            integration: true
          - perl: 5.38
            integration: true

    name: Perl ${{ matrix.perl }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}

      - name: Install dependencies
        run: cpm install -g --with-all

      - name: Install dependencies for integration tests
        if: ${{ matrix.integration }}
        run: |
          cpm install -g Data::Checks
          cpm install -g Type::Tiny
          cpm install -g Moose
          cpm install -g Mouse
          cpm install -g Moo
          cpm install -g Specio

      - run: perl Build.PL
      - run: ./Build
      - run: ./Build test

      - name: Run coverage
        if: ${{ matrix.coverage }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cpm install -g Devel::Cover::Report::Coveralls
          cover -test -report coveralls -ignore_re '^/opt'
